### ISSUE TITLE
Add relevant Issue Ids to tasks in IET-HF.md

### ISSUE THREAD

**Issue by rlacko58** [BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq#27] opened 2021-05-08 12:37 UTC
"We should link the relevant issue numbers to each task we plan to do."
https://github.com/BME-MIT-IET/iet-hf2021-v-dqw4w9wgxcq/pull/17#pullrequestreview-654987731

**Comment by kurucz-gyuri** [comment] 2021-05-08 12:52
Duplicate of #5

**Closed as completed by kurucz-gyuri** 2021-05-08 12:52 UTC
